language: node_js
node_js:
  - 'stable'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --ignore-scripts

script:
  - yarn build
